version: '3'

services:
  db:
    image: postgres:latest
    container_name: luxonis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1Q2W3E4r!
      POSTGRES_DB: scrapy_db
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
